version: '3'

services: 
  minix-builder: 
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ..:/workspace
    command: bash -c "cd minix && ./releasetools/x86_hdimage.sh"
    stdin_open: true
